#!/usr/bin/env python3
"""Build proposals from analysis results.

Takes the JSON output of all three analysis scripts (config, transcripts,
memory) and produces a ready-to-present list of proposals. This moves the
heavy cross-referencing, threshold filtering, and impact scoring from
LLM processing time to zero-cost Python execution.

Usage:
    python3 build-proposals.py --config <config.json> --transcripts <transcripts.json> --memory <memory.json> [--dismissed <dismissed.json>] [--pending <pending.json>]

Or pipe combined JSON:
    python3 build-proposals.py --combined <combined.json>

Output: JSON object with "proposals" array and "context_health" summary.
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Evidence thresholds
# ---------------------------------------------------------------------------

THRESHOLDS = {
    "skill": {"min_occurrences": 4, "min_sessions": 3},
    "hook": {"min_occurrences": 5, "min_sessions": 3},
    "rule": {"min_occurrences": 3, "min_sessions": 2},
    "claude_md_entry": {"min_occurrences": 3, "min_sessions": 2},
}


# ---------------------------------------------------------------------------
# Text similarity for cross-referencing
# ---------------------------------------------------------------------------

def _tokenize(text: str) -> set:
    """Simple word tokenization, lowercased, alpha-only."""
    return {w.lower() for w in re.findall(r'[a-zA-Z]{3,}', text)}


def _similarity(text_a: str, text_b: str) -> float:
    """Jaccard similarity between two texts."""
    tokens_a = _tokenize(text_a)
    tokens_b = _tokenize(text_b)
    if not tokens_a or not tokens_b:
        return 0.0
    intersection = tokens_a & tokens_b
    union = tokens_a | tokens_b
    return len(intersection) / len(union)


def _matches_existing(pattern_text: str, existing_items: List[Dict],
                      threshold: float = 0.3) -> Optional[Dict]:
    """Check if a pattern matches an existing skill/agent/hook.

    Returns the matching item if found, None otherwise.
    Checks both description and full content for semantic overlap.
    """
    for item in existing_items:
        # Check against name
        name = item.get("name", "")
        if name and _similarity(pattern_text, name) > 0.4:
            return item

        # Check against description
        desc = item.get("description", "")
        if desc and _similarity(pattern_text, desc) > threshold:
            return item

        # Check against full content (more lenient threshold)
        content = item.get("content", "")
        if content and _similarity(pattern_text, content) > 0.2:
            return item

    return None


# ---------------------------------------------------------------------------
# Impact scoring
# ---------------------------------------------------------------------------

def _score_impact(proposal_type: str, occurrences: int = 0,
                  sessions: int = 0, severity: str = "") -> str:
    """Score a proposal's impact as high, medium, or low."""
    if proposal_type == "skill":
        if occurrences >= 8 or sessions >= 6:
            return "high"
        elif occurrences >= 4:
            return "medium"
        return "low"

    if proposal_type == "hook":
        if severity == "high":
            return "high"
        return "medium"

    if proposal_type == "skill_update":
        return "medium"

    if proposal_type in ("rule", "claude_md_entry"):
        if occurrences >= 5 or sessions >= 4:
            return "high"
        return "medium"

    if proposal_type == "reference_doc":
        return "low"

    return "medium"


# ---------------------------------------------------------------------------
# Template generators for suggested content
# ---------------------------------------------------------------------------

def _generate_skill_content(pattern: str, examples: List[str]) -> str:
    """Generate a draft skill from a repeated prompt pattern."""
    # Derive a name from the pattern
    name = re.sub(r'[^a-z0-9]+', '-', pattern.lower()).strip('-')[:30]

    example_text = ""
    if examples:
        example_text = "\n".join(f"- \"{ex}\"" for ex in examples[:3])

    return f"""---
name: {name}
description: >-
  {pattern}. Use when the user asks to {pattern.lower()}.
---

<!-- Draft generated by Forge — test and iterate -->

## Steps

1. [TODO: Define the specific steps for this workflow]

## Trigger phrases

Users typically say:
{example_text or '- [Add common trigger phrases]'}
"""


def _generate_hook_content(gap: Dict) -> str:
    """Generate a hook JSON snippet from a config gap."""
    detail = gap.get("detail", {})
    hook_event = detail.get("hook_event", "PostToolUse")
    matcher = detail.get("matcher", "Write|Edit")
    linter = detail.get("linter", "eslint")

    if linter == "prettier" or "format" in linter.lower():
        command = f'npx prettier --write "$CLAUDE_TOOL_INPUT_FILE_PATH"'
    elif linter == "eslint":
        command = (
            f'npx eslint --no-warn-ignored --quiet '
            f'--max-warnings 0 "$CLAUDE_FILE_PATHS" 2>/dev/null || '
            f'echo "ESLint issues found in edited file."'
        )
    else:
        command = f'{linter} "$CLAUDE_TOOL_INPUT_FILE_PATH"'

    return json.dumps({
        "hooks": {
            hook_event: [{
                "matcher": matcher,
                "hooks": [{
                    "type": "command",
                    "command": command,
                    "timeout": 10
                }]
            }]
        }
    }, indent=2)


def _generate_rule_content(issue: Dict) -> str:
    """Generate a rule file from a placement issue."""
    content = issue.get("content", "")
    suggestion = issue.get("suggestion", "")
    return f"""---
path: "**/*"
---

{content}
"""


# ---------------------------------------------------------------------------
# Proposal builders — one per source type
# ---------------------------------------------------------------------------

def _build_from_gaps(config: Dict, existing_hooks: List[Dict]) -> List[Dict]:
    """Build proposals from config audit gaps."""
    proposals = []
    for gap in config.get("gaps", []):
        gap_type = gap.get("type", "")
        detail = gap.get("detail", {})

        if gap_type == "missing_hook":
            # Check if hook already exists
            hook_event = detail.get("hook_event", "")
            matcher = detail.get("matcher", "")
            already_exists = any(
                h.get("event") == hook_event and
                matcher in h.get("matcher", "")
                for h in existing_hooks
            )
            if already_exists:
                continue

            linter = detail.get("linter", "unknown")
            proposals.append({
                "id": f"auto-{linter}-hook",
                "type": "hook",
                "impact": _score_impact("hook", severity=gap.get("severity", "")),
                "confidence": "high",
                "description": f"Auto-{linter} hook after Edit/Write operations",
                "evidence_summary": (
                    f"{linter.capitalize()} configured but no {hook_event} "
                    f"hook exists — lint issues won't surface until manual run"
                ),
                "suggested_content": _generate_hook_content(gap),
                "suggested_path": ".claude/settings.json",
                "status": "pending",
            })

    return proposals


def _build_from_repeated_prompts(transcripts: Dict,
                                  existing_skills: List[Dict]) -> List[Dict]:
    """Build proposals from repeated prompt patterns."""
    proposals = []
    candidates = transcripts.get("candidates", {})

    for pattern in candidates.get("repeated_prompts", []):
        text = pattern.get("canonical_text",
                           pattern.get("pattern", ""))
        occurrences = pattern.get("total_occurrences",
                                   pattern.get("occurrences", 0))
        # sessions can be an int or an array of session IDs
        sessions_val = pattern.get("session_count",
                                    pattern.get("sessions", 0))
        sessions = (len(sessions_val) if isinstance(sessions_val, list)
                    else sessions_val)
        examples_raw = pattern.get("example_messages",
                                    pattern.get("evidence", []))
        # Extract user_message strings from evidence dicts
        examples = []
        for ex in examples_raw:
            if isinstance(ex, dict):
                msg = ex.get("user_message", "")
                if msg:
                    examples.append(msg[:100])
            elif isinstance(ex, str):
                examples.append(ex[:100])

        # Skip system-injected patterns (skill invocations, plugin content)
        if any(skip in text.lower() for skip in [
            "base directory for this skill",
            "you are running forge",
            "claude_plugin_root",
            "follow these steps in order",
        ]):
            continue
        # Also check evidence for system content
        if examples and all(
            any(skip in ex.lower() for skip in [
                "base directory for this skill",
                "you are running forge",
            ])
            for ex in examples
        ):
            continue

        # Check thresholds
        thresh = THRESHOLDS["skill"]
        if occurrences < thresh["min_occurrences"]:
            continue
        if sessions < thresh["min_sessions"]:
            continue

        # Cross-reference against existing skills
        match = _matches_existing(text, existing_skills)
        if match:
            # Existing skill covers this pattern — skip or suggest update
            match_name = match.get("name", "unknown")
            match_format = match.get("format", "skill")
            if match_format == "legacy_command":
                # Suggest migration
                proposals.append({
                    "id": f"migrate-{match_name}-to-skill",
                    "type": "skill_update",
                    "impact": "medium",
                    "confidence": "high",
                    "description": (
                        f"Migrate legacy command /{match_name} to modern "
                        f"skill format"
                    ),
                    "evidence_summary": (
                        f"/{match_name} is a .claude/commands/ file — "
                        f"modern skills have richer metadata and trigger "
                        f"detection"
                    ),
                    "suggested_content": "",  # LLM generates migration
                    "suggested_path": match.get("path", ""),
                    "status": "pending",
                })
            continue  # Don't propose a duplicate skill

        # New skill proposal
        name = re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')[:30]
        proposals.append({
            "id": f"{name}-skill",
            "type": "skill",
            "impact": _score_impact("skill", occurrences, sessions),
            "confidence": "high" if occurrences >= 6 else "medium",
            "description": f"Create /{name} skill from repeated pattern",
            "evidence_summary": (
                f'"{text}" — {occurrences} occurrences across '
                f'{sessions} sessions'
            ),
            "suggested_content": _generate_skill_content(text, examples),
            "suggested_path": f".claude/skills/{name}/SKILL.md",
            "status": "pending",
        })

    return proposals


def _build_from_corrections(transcripts: Dict,
                             existing_skills: List[Dict]) -> List[Dict]:
    """Build proposals from correction patterns."""
    proposals = []
    candidates = transcripts.get("candidates", {})

    for correction in candidates.get("corrections", []):
        theme = correction.get("theme", correction.get("pattern", ""))
        occurrences = correction.get("total_occurrences",
                                      correction.get("occurrences", 0))
        sessions_val = correction.get("session_count",
                                       correction.get("sessions", 0))
        sessions = (len(sessions_val) if isinstance(sessions_val, list)
                    else sessions_val)

        thresh = THRESHOLDS["rule"]
        if occurrences < thresh["min_occurrences"]:
            continue
        if sessions < thresh["min_sessions"]:
            continue

        name = re.sub(r'[^a-z0-9]+', '-', theme.lower()).strip('-')[:30]
        proposals.append({
            "id": f"{name}-rule",
            "type": "rule",
            "impact": _score_impact("rule", occurrences, sessions),
            "confidence": "high" if occurrences >= 5 else "medium",
            "description": f"Add rule: {theme}",
            "evidence_summary": (
                f"Corrected {occurrences} times across {sessions} sessions"
            ),
            "suggested_content": "",  # LLM refines the rule content
            "suggested_path": f".claude/rules/{name}.md",
            "status": "pending",
        })

    return proposals


def _build_from_memory(memory: Dict) -> List[Dict]:
    """Build proposals from memory analysis (promotable notes)."""
    proposals = []
    auto_memory = memory.get("auto_memory", {})

    for note in auto_memory.get("promotable_notes", []):
        topic = note.get("topic", "unknown")
        suggestion = note.get("suggested_artifact", "rule")
        content = note.get("content", "")

        name = re.sub(r'[^a-z0-9]+', '-', topic.lower()).strip('-')[:30]
        proposals.append({
            "id": f"promote-{name}",
            "type": suggestion,
            "impact": "medium",
            "confidence": "medium",
            "description": f"Promote memory note to {suggestion}: {topic}",
            "evidence_summary": f"Auto-memory note about {topic}",
            "suggested_content": content,
            "suggested_path": f".claude/rules/{name}.md",
            "status": "pending",
        })

    return proposals


# ---------------------------------------------------------------------------
# Context health summary
# ---------------------------------------------------------------------------

def _build_context_health(config: Dict) -> Dict[str, Any]:
    """Build a compact context health summary from config audit."""
    budget = config.get("context_budget", {})
    tech = config.get("tech_stack", {})
    placement = config.get("placement_issues", [])

    health = {
        "claude_md_lines": budget.get("claude_md_lines", 0),
        "rules_count": budget.get("rules_count", 0),
        "skills_count": budget.get("skills_count", 0),
        "hooks_count": budget.get("hooks_count", 0),
        "agents_count": budget.get("agents_count", 0),
        "tier1_lines": budget.get("estimated_tier1_lines", 0),
        "over_budget": budget.get("estimated_tier1_lines", 0) > 150,
        "tech_stack": tech.get("detected", []),
        "placement_note_count": len(placement),
    }

    # Build a one-liner
    parts = []
    lines = health["claude_md_lines"]
    parts.append(f"CLAUDE.md: {lines} lines")
    if health["over_budget"]:
        parts.append("(over 150-line budget)")

    counts = []
    for key, label in [("rules_count", "rules"), ("skills_count", "skills"),
                        ("hooks_count", "hooks"), ("agents_count", "agents")]:
        counts.append(f'{health[key]} {label}')
    parts.append(", ".join(counts))

    if health["placement_note_count"] > 0:
        parts.append(
            f'{health["placement_note_count"]} placement suggestions'
        )

    health["summary"] = ". ".join(parts) + "."
    return health


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def build_proposals(config: Dict, transcripts: Dict, memory: Dict,
                    dismissed: List[Dict],
                    pending: List[Dict]) -> Dict[str, Any]:
    """Build the full proposal list from all analysis sources."""
    existing_skills = config.get("existing_skills", [])
    existing_agents = config.get("existing_agents", [])
    existing_hooks = config.get("existing_hooks", [])

    # Collect dismissed IDs and themes for filtering
    dismissed_ids = {d.get("id", "") for d in dismissed}
    dismissed_themes = set()
    for d in dismissed:
        theme = d.get("description", "")
        if theme:
            dismissed_themes.add(theme.lower())

    # Build proposals from all sources
    all_proposals = []
    all_proposals.extend(_build_from_gaps(config, existing_hooks))
    all_proposals.extend(
        _build_from_repeated_prompts(transcripts, existing_skills)
    )
    all_proposals.extend(
        _build_from_corrections(transcripts, existing_skills)
    )
    all_proposals.extend(_build_from_memory(memory))

    # Filter dismissed
    filtered = []
    for p in all_proposals:
        if p["id"] in dismissed_ids:
            continue
        if p.get("description", "").lower() in dismissed_themes:
            continue
        filtered.append(p)

    # Filter low impact
    filtered = [p for p in filtered if p.get("impact") != "low"]

    # Deduplicate against pending proposals
    pending_ids = {pp.get("id", "") for pp in pending
                   if pp.get("status") == "pending"}
    final = [p for p in filtered if p["id"] not in pending_ids]

    # Merge with existing pending proposals
    for pp in pending:
        if pp.get("status") == "pending":
            final.append(pp)

    # Sort: high impact first, then medium
    impact_order = {"high": 0, "medium": 1, "low": 2}
    final.sort(key=lambda p: impact_order.get(p.get("impact", "medium"), 1))

    # Build context health
    context_health = _build_context_health(config)

    return {
        "proposals": final,
        "context_health": context_health,
        "stats": {
            "total_candidates": len(all_proposals),
            "after_dedup": len(filtered),
            "final_count": len(final),
            "sessions_analyzed": transcripts.get("sessions_analyzed", 0),
        },
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _load_json_file(path: str) -> Dict:
    """Load JSON from a file path, returning empty dict on failure."""
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _load_json_list(path: str) -> List[Dict]:
    """Load a JSON array from a file path, returning empty list on failure."""
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        return []
    except (OSError, json.JSONDecodeError):
        return []


def main():
    parser = argparse.ArgumentParser(
        description="Build proposals from Forge analysis results"
    )
    parser.add_argument("--config", type=str, default=None,
                        help="Path to config audit JSON")
    parser.add_argument("--transcripts", type=str, default=None,
                        help="Path to transcript analysis JSON")
    parser.add_argument("--memory", type=str, default=None,
                        help="Path to memory analysis JSON")
    parser.add_argument("--dismissed", type=str, default=None,
                        help="Path to dismissed.json")
    parser.add_argument("--pending", type=str, default=None,
                        help="Path to pending.json")
    parser.add_argument("--combined", type=str, default=None,
                        help="Path to combined JSON (all three analyses)")
    args = parser.parse_args()

    if args.combined:
        combined = _load_json_file(args.combined)
        config = combined.get("config", {})
        transcripts = combined.get("transcripts", {})
        memory = combined.get("memory", {})
    else:
        config = _load_json_file(args.config) if args.config else {}
        transcripts = (_load_json_file(args.transcripts)
                       if args.transcripts else {})
        memory = _load_json_file(args.memory) if args.memory else {}

    dismissed = (_load_json_list(args.dismissed)
                 if args.dismissed else [])
    pending = _load_json_list(args.pending) if args.pending else []

    result = build_proposals(config, transcripts, memory, dismissed, pending)
    json.dump(result, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
